name: 'Release Gateway'
description: 'Control your releases using push notification approvals, daily schedules and more'
inputs:
  environment-name:
    description: 'Name of the environment this release is targeting (eg: prod, test, dev, etc)'
    required: false
  code-version:
    description: 'Override the identifier used for the version of code being released (eg: v1, v2.4.2, GIT_SHA etc)'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
