name: Code Quality

on: push

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: NPM Install
        run: npm install
      - name: Run linters
        run: npm run lint
  test:
    name: Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: NPM Install
        run: npm install
      - name: Run Tests
        run: npm run test
